const data = [
  { question: "꼬막한상", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1484109288/photo?filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "꼬막한상", requirement: "图片视频剪辑网址地图相关中的10位数字", answer: "1484109288" },
  { question: "꼬막한상", requirement: "URL：交通停车[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1484109288/location?entry=plt&filter=parking" },
  { question: "꼬막한상", requirement: "数字URL[URL 주소]10자리까지 URL", answer: "https://m.place.naver.com/restaurant/1484109288" },
  { question: "꼬막한상", requirement: "【전화】12位连续电话[12개의]", answer: "050713342868" },
  { question: "꼬막한상", requirement: "第2个加油站名字？2번째 주유소인", answer: "대곶IC주유소" },
  { question: "꼬막한상", requirement: "评论访客第10个以内的名字", answer: "해도달도43" },
  { question: "꼬막한상 강화", requirement: "URL：交通公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1484109288/location?entry=plt&filter=transportation" },
  { question: "부평 유리막코팅", requirement: "", answer: "진달래공원" },
  { question: "부천 미용실 매직", requirement: "", answer: "계남공원" },
  { question: "부천 옥길동 누수", requirement: "周边名所第3个叫什么？", answer: "범박동성당" },
  { question: "강서구 누수탐지 양천로", requirement: "", answer: "개화사" },
  { question: "쿠시인 본점", requirement: "", answer: "영등포전통시장" },
  { question: "쿠시인 본점", requirement: "URL：交通公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1170122861/location?filter=transportation" },
  { question: "쿠시인 본점", requirement: "URL：交通停车[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1547042129/photo?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "쿠시인 본점", requirement: "URL：图片视频[사진]>[클립]", answer: "https://m.place.naver.com/restaurant/1170122861/photo?filterType=%ED%81%B4%EB%A6%BD" },
  { question: "쿠시인 본점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1170122861/photo?filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "쿠시인 본점", requirement: "第21个菜单的价格是？", answer: "4100" },
  { question: "쿠시인 본점", requirement: "第12个菜单价格", answer: "7000" },
  { question: "쿠시인 본점", requirement: "数字URL[URL 주소]10자리까지 URL", answer: "https://m.place.naver.com/restaurant/1170122861" },
  { question: "쿠시인 본점", requirement: "图片视频剪辑网址地图相关中的10位数字", answer: "1170122861" },
  { question: "쿠시인 본점", requirement: "评价访客第10位的名字？", answer: "똘똘이양일상" },
  { question: "쿠시인 본점", requirement: "第6个停车场名字？", answer: "영등포동제1공영주차장" },
  { question: "쿠시인 본점", requirement: "【전화】12位连续电话[12개의]", answer: "050713016234" },
  { question: "쿠시인 본점", requirement: "附近的상회名字是什麼 (4個字)", answer: "복음상회" },
  { question: "쿠시인 본점", requirement: "可以预定的最少人数➕最多人数", answer: "13" },
  { question: "건강밥상심마니 배곧점", requirement: "", answer: "시흥배곧동우체국" },
  { question: "건강밥상심마니 배곧점", requirement: "第4个停车场叫什么？", answer: "다인로얄팰리스6차민영주차장" },
  { question: "건강밥상심마니 배곧점", requirement: "附近的지구대（警察局）", answer: "배곧지구대" },
  { question: "건강밥상심마니 배곧점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1583227729/photo?filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "건강밥상심마니 배곧점", requirement: "URL：图片编辑[사진]>[클립]", answer: "https://m.place.naver.com/restaurant/1583227729/photo?entry=plt&filterType=%ED%81%B4%EB%A6%BD" },
  { question: "건강밥상심마니 배곧점", requirement: "URL：交通公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1583227729/location?entry=pll&filter=transportation" },
  { question: "건강밥상심마니 배곧점", requirement: "地图周边公交网址中的10位数字", answer: "1583227729" },
  { question: "하이원 소고기 맛집", requirement: "", answer: "보성사" },
  { question: "분당 딱새우 맛집", requirement: "", answer: "SG타워오피스텔" },
  { question: "서파장어랜드", requirement: "URL：交通公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1435911210/location?entry=plt&filter=transportation" },
  { question: "서파장어랜드", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1435911210/photo?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "서파장어랜드", requirement: "URL：交通停车[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1435911210/location?entry=plt&filter=parking" },
  { question: "서파장어랜드", requirement: "第5个菜单的价格？", answer: "8000" },
  { question: "서파장어랜드", requirement: "第2个加油站SK什么名字？", answer: "SK엔크린고인돌주유소" },
  { question: "서파장어랜드", requirement: "前十条评论名字含“ㅁㄴㅇㄴ”", answer: "모니언니" },
  { question: "서파장어랜드", requirement: "", answer: "유토펌프카" },
  { question: "서파장어랜드", requirement: "附近的咖啡厅名字？[카페] ", answer: "피움카페" },
  { question: "서파장어랜드", requirement: "数字URL[URL 주소]10자리까지 URL", answer: "https://m.place.naver.com/restaurant/1435911210" },
  { question: "서파장어랜드", requirement: "图片视频剪辑网址地图相关中的10位数字", answer: "1435911210" },
  { question: "서파장어랜드", requirement: "【전화】12位连续电话[12개의]", answer: "050713381239" },
  { question: "사쿠라테이엔 판교본점", requirement: "URL：交通公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1547042129/location?entry=plt&filter=transportation" },
  { question: "사쿠라테이엔 판교본점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1547042129/photo?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "사쿠라테이엔 판교본점", requirement: "", answer: "SG타워오피스텔" },
  { question: "사쿠라테이엔 판교본점", requirement: "评论区第10位作者名［ㅁㄴㅇㄴ］", answer: "모니언니" },
  { question: "사쿠라테이엔 판교본점", requirement: "第5个停车场名字？", answer: "아브뉴프랑판교점제1주차장" },
  { question: "사쿠라테이엔 판교본점", requirement: "地图企业位置附近的5个字餐厅[5글자]", answer: "오뚜기식당" },
  { question: "사쿠라테이엔 판교본점", requirement: "图片视频剪辑网址地图相关中的10位数字", answer: "1547042129" },
  { question: "사쿠라테이엔 판교본점", requirement: "URL：图片剪辑[사진]>[클립]", answer: "https://m.place.naver.com/restaurant/1547042129/photo?entry=plt&filterType=%ED%81%B4%EB%A6%BD" },
  { question: "사쿠라테이엔 판교본점", requirement: "URL：交通停车[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1547042129/location?entry=plt&filter=parking" },
  { question: "사쿠라테이엔 판교본점", requirement: "第17个菜单价格", answer: "22000" },
  { question: "사쿠라테이엔 판교본점", requirement: "第23个菜单的价格？", answer: "35000" },
  { question: "사쿠라테이엔 판교본점", requirement: "预约人数最多+最少", answer: "22" },
  { question: "사쿠라테이엔 판교본점", requirement: "数字URL[URL 주소]10자리까지 URL", answer: "https://m.place.naver.com/restaurant/1547042129" },
  { question: "사쿠라테이엔 판교본점", requirement: "【전화】12位连续电话[12개의]", answer: "050713536234" },
  { question: "사쿠라테이엔 판교2호점", requirement: "URL：交通停车[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1697419071/location?entry=plt&filter=parking" },
  { question: "사쿠라테이엔 판교2호점", requirement: "URL：交通公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1697419071/location?entry=plt&filter=transportation" },
  { question: "사쿠라테이엔 판교2호점 ", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1697419071/photo?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "사쿠라테이엔 판교2호점", requirement: "URL：图片剪辑[사진]>[클립]", answer: "https://m.place.naver.com/restaurant/1697419071/photo?entry=plt&filterType=%ED%81%B4%EB%A6%BD" },
  { question: "사쿠라테이엔 판교2호점", requirement: "地图停车场网址的10位数字", answer: "1697419071" },
  { question: "사쿠라테이엔 판교2호점", requirement: "【전화】12位连续电话[12개의]", answer: "050713673005" },
  { question: "사쿠라테이엔 판교2호점", requirement: "第7个停车场的名字？7번째  주차장인", answer: "판교테크원주차장" },
  { question: "사쿠라테이엔 문정점", requirement: "第2个停车场叫什么？", answer: "문정엠스테이트관리단" },
  { question: "사쿠라테이엔 문정점", requirement: "URL：交通停车[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1049712930/location?entry=plt&filter=parking" },
  { question: "사쿠라테이엔 문정점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1049712930/photo?entry=pll&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "사쿠라테이엔 문정점", requirement: "URL：图片剪辑[사진]>[클립]", answer: "https://m.place.naver.com/restaurant/1049712930/photo?entry=plt&filterType=%ED%81%B4%EB%A6%BD" },
  { question: "사쿠라테이엔 문정점", requirement: "URL: 地图公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1049712930/location?entry=plt&filter=transportation" },
  { question: "사쿠라테이엔 문정점", requirement: "地图停车场网址中的10位数字", answer: "1049712930" },
  { question: "사쿠라테이엔 문정점", requirement: "【전화】12位连续电话[12개의]", answer: "050713348360" },
  { question: "사쿠라테이엔 문정점", requirement: "附近的내과의원叫什麼名字(9個字)", answer: "송파베스트내과의원" },
  { question: "사쿠라테이엔 문정점", requirement: "第12个菜单的价格", answer: "20000" },
  { question: "사쿠라테이엔 문정점", requirement: "前10条评论名字含[ㅁㄲㅂ1ㅉ]", answer: "먹깨비1짱" },
  { question: "사쿠라테이엔 문정점", requirement: "预约最小人数+最大人数", answer: "15명 " },
  { question: "사쿠라테이엔 일산풍산점", requirement: "URL：交通停车[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1618831017/location?entry=plt&filter=parking" },
  { question: "사쿠라테이엔 일산풍산점", requirement: "URL：交通公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1618831017/location?entry=pll&filter=transportation" },
  { question: "사쿠라테이엔 일산풍산점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1618831017/photo?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "사쿠라테이엔 일산풍산점", requirement: "URL：图片剪辑[사진]>[클립]", answer: "https://m.place.naver.com/restaurant/1618831017/photo?entry=plt&filterType=%ED%81%B4%EB%A6%BD" },
  { question: "사쿠라테이엔 일산풍산점", requirement: "地图停车场网址的10位数字", answer: "1618831017" },
  { question: "사쿠라테이엔 일산풍산점", requirement: "【전화】12位连续电话[12개의]", answer: "050713407614" },
  { question: "사쿠라테이엔 일산풍산점", requirement: "附近的炸猪排店名？5个字", answer: "이도돈까스" },
  { question: "사쿠라테이엔 일산풍산점", requirement: "第2个停车场名称2번째 주차장인", answer: "카카오T이마트풍산점주차장" },
  { question: "사쿠라테이엔 오목교점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1650023028/photo?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "사쿠라테이엔 오목교점", requirement: "URL：交通公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1650023028/location?entry=plt&filter=transportation" },
  { question: "사쿠라테이엔 오목교점", requirement: "URL：图片剪辑[사진]>[클립]", answer: "https://m.place.naver.com/restaurant/1650023028/photo?entry=plt&filterType=%ED%81%B4%EB%A6%BD" },
  { question: "사쿠라테이엔 오목교점", requirement: "URL：交通停车[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1650023028/location?entry=plt&filter=parking" },
  { question: "사쿠라테이엔 오목교점", requirement: "第13个菜单价格", answer: "30000" },
  { question: "사쿠라테이엔 오목교점", requirement: "附近的병원（医院）", answer: "이대목동병원(报错）" },
  { question: "사쿠라테이엔 오목교점", requirement: "地图停车场网址的10位数字", answer: "1650023028" },
  { question: "사쿠라테이엔 오목교 주차", requirement: "URL：交通公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1650023028/location?entry=plt&filter=transportation" },
  { question: "사쿠라테이엔 오목교직영점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1650023028/photo?entry=pll&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "사쿠라테이엔 오목교직영점", requirement: "URL: 地图公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1650023028/location?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81&filter=transportation" },
  { question: "사쿠라테이엔 오목교직영점", requirement: "URL：地图停车场[지도]> [주차장]", answer: "https://m.place.naver.com/restaurant/1650023028/location?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81&filter=parking" },
  { question: "사쿠라테이엔 오목교직영점", requirement: "数字URL[URL 주소]10자리까지 URL", answer: "https://m.place.naver.com/restaurant/1650023028" },
  { question: "사쿠라테이엔 오목교직영점", requirement: "第24个菜单的价格번째 메뉴의", answer: "17000" },
  { question: "사쿠라테이엔 오목교직영점", requirement: "图片视频剪辑网址地图相关中的10位数字", answer: "1650023028" },
  { question: "사쿠라테이엔 오목교직영점", requirement: "第23个菜单的价格23번째 메뉴의", answer: "25000" },
  { question: "사쿠라테이엔 오목교직영점", requirement: "附近牙科诊所名和医生名字？（7个字）", answer: "서울탑치과의원" },
  { question: "사쿠라테이엔 오목교직영점", requirement: "第6个停车场名字？", answer: "청학빌딩주차장" },
  { question: "축석장어랜드 포천 광릉수목원점", requirement: "图片视频剪辑网址地图相关中的10位数字", answer: "1079923612" },
  { question: "축석장어랜드 포천 광릉수목원점", requirement: "URL：交通公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1079923612/location?entry=pll&filter=transportation" },
  { question: "축석장어랜드 포천 광릉수목원점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1079923612/photo?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "축석장어랜드 포천 광릉수목원점", requirement: "URL：交通停车[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1079923612/location?entry=plt&filter=parking" },
  { question: "축석장어랜드 포천 광릉수목원점", requirement: "数字URL[URL 주소]10자리까지 URL", answer: "https://m.place.naver.com/restaurant/1079923612" },
  { question: "축석장어랜드 포천 광릉수목원점", requirement: "附近的汽车相关叫什么?[모터스]", answer: "미르모터스" },
  { question: "축석장어랜드 포천 광릉수목원점", requirement: "附近的낚시叫什麼名字(4个字)", answer: "그린낚시" },
  { question: "축석장어랜드 포천 광릉수목원점", requirement: "第3个加油站叫什么？", answer: "신화에너지제일주유소" },
  { question: "남산드럼통 본점", requirement: "", answer: "동인주차장" },
  { question: "영등포시장역 이자카야", requirement: "URL：交通公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1490628382/location?entry=pll&filter=transportation" },
  { question: "한식뷔페&카페 봄날", requirement: "图片视频、剪辑网址10位数字？", answer: "1609696310" },
  { question: "한식뷔페&카페 봄날", requirement: "URL：交通公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1609696310/location?entry=pll&filter=transportation" },
  { question: "한식뷔페&카페 봄날", requirement: "URL：图片剪辑[사진]>[클립]", answer: "https://m.place.naver.com/restaurant/1609696310/photo?filterType=%ED%81%B4%EB%A6%BD" },
  { question: "한식뷔페&카페 봄날", requirement: "URL: 照片访客标签[사진]>[방문자]", answer: "https://m.place.naver.com/restaurant/1609696310/photo?entry=pll&filterType=%EB%B0%A9%EB%AC%B8%EC%9E%90" },
  { question: "한식뷔페&카페 봄날", requirement: "第21个菜单价格？", answer: "4800" },
  { question: "한식뷔페&카페 봄날", requirement: "附近的教堂名字(힌트 : 6글자)", answer: "신촌장로교회" },
  { question: "한식뷔페&카페 봄날", requirement: "第4个加油站4번째 주유소인 SK", answer: "SK엔크린자곡셀프주유소" },
  { question: "종로5가 빈대떡 맛집", requirement: "URL:  设置为公共区域", answer: "https://naver.me/xR23Xorv" },
  { question: "365효플란트치과의원", requirement: "", answer: "동매산" },
  { question: "산본 네일 제약", requirement: "", answer: "철쭉공원" },
  { question: "뉴엔치과의원   ", requirement: "", answer: "역삼까치공원" },
  { question: "자은동 인테리어 업체 추천", requirement: "", answer: "용궁암" },
  { question: "인천 서구커튼커튼블라인드갤러리검단점 5529", requirement: "", answer: "아라보타닉파크" },
  { question: "커피스니퍼 클래식 성수점", requirement: "", answer: "서울숲디타워주차장" },
  { question: "가야해장 용산본점", requirement: "第6个地点", answer: "열정도" },
  { question: "단양쏘가리매운탕", requirement: "", answer: "대성산산림욕장" },
  { question: "미사역 감자전 맛집", requirement: "", answer: "미사강변성당" },
  { question: "양재동부동산", requirement: "", answer: "서울안심정사" },
  { question: "범계 네일 내성", requirement: "", answer: "평촌공원" },
  { question: "와이앤유 필라테스", requirement: "", answer: "이천설봉산성" },
  { question: "단양 그집쏘가리", requirement: "", answer: "대성산산림욕장" },
  { question: "황소식육실비식당", requirement: "附近第6个名所", answer: "보성사" },
  { question: "황소식육실비식당 한우하이원", requirement: "", answer: "보성사" },
  { question: "설화정생갈비", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1025209848/photo?filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "설화정생갈비", requirement: "URL：交通公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1025209848/location?filter=transportation" },
  { question: "설화정생갈비", requirement: "URL：图片剪辑[사진]>[클립]", answer: "https://m.place.naver.com/restaurant/1025209848/photo?filterType=%ED%81%B4%EB%A6%BD" },
  { question: "설화정생갈비", requirement: "数字URL[URL 주소]10자리까지 URL", answer: "https://m.place.naver.com/restaurant/1025209848" },
  { question: "설화정생갈비", requirement: "图片视频剪辑网址地图相关中的10位数字", answer: "1025209848" },
  { question: "설화정생갈비", requirement: "【전화】12位连续电话[12개의]", answer: "050714001237" },
  { question: "설화정생갈비", requirement: "第3个停车场叫什么？", answer: "파주더케이빌딩주차장" },
  { question: "설화정생갈비", requirement: "第19个菜的价格", answer: "3000" },
  { question: "설화정생갈비", requirement: "访客评论前10名名称带有43的全名", answer: "해도달도43" },
  { question: "설화정생갈비 예약", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1025209848/photo?filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "설화정생갈비 예약", requirement: "图片视频、编辑网址的10位数字", answer: "1025209848" },
  { question: "셀엑티브", requirement: "제조사（制造商）", answer: "필인터파마" },
  { question: "밴스의원 수원", requirement: "周边景点的第4处地点[네 번째]", answer: "대유평공원" },
  { question: "박가네 빈대떡", requirement: "第5个地点", answer: "훈련원공원" },
  { question: "건대역레오정형외과의원", requirement: "周边景点的第4处地点[네 번째]", answer: "일감호" },
  { question: "숙대입구 맛집 한우육회", requirement: "", answer: "동인주차장" },
  { question: "수그릴 파주헤이리 위치", requirement: "URL：交通停车[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1964609322/location?entry=plt&filter=parking" },
  { question: "수그릴 파주헤이리 주차", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1964609322/photo?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81 " },
  { question: "수그릴 파주헤이리본점", requirement: "URL：交通停车[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1964609322/location?entry=plt&filter=parking" },
  { question: "수그릴 파주헤이리본점", requirement: "URL：交通公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1964609322/location?entry=plt&filter=transportation" },
  { question: "수그릴 파주헤이리본점", requirement: "URL：图片剪辑[사진]>[클립]", answer: "https://m.place.naver.com/restaurant/1964609322/photo?entry=plt&filterType=%ED%81%B4%EB%A6%BD" },
  { question: "수그릴 파주헤이리본점", requirement: "数字URL[URL 주소]10자리까지 URL", answer: "https://m.place.naver.com/restaurant/1964609322" },
  { question: "수그릴 파주헤이리본점", requirement: "图片视频剪辑网址地图相关中的10位数字", answer: "1964609322" },
  { question: "수그릴 파주헤이리본점", requirement: "【전화】12位连续电话[12개의]", answer: "050713470846" },
  { question: "수그릴 파주헤이리본점", requirement: "附近的三岔路口叫什么?[삼거리]", answer: "도레미미디어삼거리" },
  { question: "수그릴 파주헤이리본점", requirement: "第17个菜的价格", answer: "9000" },
  { question: "수그릴 파주헤이리본점", requirement: "前10中的一位访客用户名［ㅇㅍㄷㅅ4］", answer: "일편단심4" },
  { question: "쭈앤쭈 홍대점", requirement: "第3个HD加油站叫什么名字", answer: "청원주유소" },
  { question: "식스틴 휘트니스", requirement: "URL：图片剪辑[사진]>[클립]", answer: "https://m.place.naver.com/place/1004973811/photo?entry=pll&filterType=%ED%81%B4%EB%A6%BD" },
  { question: "식스틴 휘트니스", requirement: "图片剪辑、视频网址10位数？", answer: "1004973811" },
  { question: "식스틴 휘트니스", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/place/1004973811/photo?entry=pll&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "성남 신촌 맛집", requirement: "URL：图片剪辑[사진]>[클립]", answer: "https://m.place.naver.com/restaurant/1609696310/photo?entry=pll&filterType=%ED%81%B4%EB%A6%BD" },
  { question: "청풍식육식당", requirement: "附近第7个名所", answer: "봉수대공원" },
  { question: "코지로", requirement: "附近第4个名所", answer: "도곡공원" },
  { question: "멜랑제", requirement: "第4个sk加油站叫什么?4번째 주유소인", answer: "대명주유소" },
  { question: "트립닷컴 인기특가상품", requirement: "", answer: "아리아케" },
  { question: "비샤인디테일링 손세차장 광택 유리막코팅실내크리닝", requirement: "附近第5个名所", answer: "진달래공원" },
  { question: "까몬 남양점", requirement: "URL：交通停车[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1541038912/location?entry=plt&filter=parking" },
  { question: "까몬 남양점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1541038912/photo?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "까몬 남양점", requirement: "URL: 地图公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1541038912/location?entry=plt&filter=parking" },
  { question: "까몬 남양점", requirement: "地图停车场网址10位数字", answer: "1541038912" },
  { question: "까몬 남양점", requirement: "附近广场的名字叫什么？[프라자]", answer: "용진프라자" },
  { question: "까몬 구미점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1283052422/photo?filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "까몬 구미점", requirement: "附近的韩国超市叫什么名字？", answer: "코리아마트" },
  { question: "까몬 구미점", requirement: "URL: 地图公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1283052422/location?filter=transportation" },
  { question: "까몬 구미점", requirement: "地图公交网址10位数字", answer: "1283052422" },
  { question: "까몬 화성향남점", requirement: "URL: 地图公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1116264521/location?entry=plt&filter=transportation" },
  { question: "까몬 화성향남점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1116264521/photo?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "까몬 화성향남점", requirement: "地图停车场网址10位数字", answer: "1116264521" },
  { question: "까몬 영종운서역점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1422713115/photo?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "까몬 영종운서역점", requirement: "URL: 地图公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1422713115/location?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81&filter=transportation" },
  { question: "까몬 영종운서역점", requirement: "URL：地图停车场[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1422713115/location?entry=plt&filter=parking" },
  { question: "까몬 영종운서역점", requirement: "地图停车场网址10位数字", answer: "1422713115" },
  { question: "까몬 영종운서역점", requirement: "附近的饼干教室叫什么?[과자교실]", answer: "로뎀트리과자교실" },
  { question: "남이섬 안반지 닭갈비", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/21642974/photo?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "남이섬 안반지 닭갈비", requirement: "URL: 地图公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/21642974/location?entry=plt&filter=transportation" },
  { question: "남이섬 안반지 닭갈비", requirement: "数字URL[URL 주소]10자리까지 URL", answer: "https://m.place.naver.com/restaurant/21642974" },
  { question: "남이섬 안반지 닭갈비", requirement: "图片视频剪辑网址地图相关中的10位数字", answer: "21642974" },
  { question: "남이섬 안반지 닭갈비", requirement: "【전화】12位连续电话[12개의]", answer: "050714103422" },
  { question: "남이섬 안반지 닭갈비", requirement: "周边景点的第5个S声母", answer: "사랑해체험마을" },
  { question: "남이섬 안반지 닭갈비", requirement: "URL：图片剪辑[사진]>[클립]", answer: "https://m.place.naver.com/restaurant/21642974/photo?entry=plt&filterType=%ED%81%B4%EB%A6%BD" },
  { question: "남이섬 안반지 닭갈비", requirement: "附近的咖啡厅叫什么?[카페]", answer: "카페평화" },
  { question: "남이섬 안반지 닭갈비", requirement: "附近第4个停车场", answer: "에덴스벨리민영주차장" },
  { question: "남이섬 안반지 닭갈비", requirement: "评论里第10位含有的作者名字", answer: "비전동피바람" },
  { question: "남이섬 안반지 닭갈비", requirement: "预约人数最少+最多“최소인원수 + 최대인원수”", answer: "23" },
  { question: "평촌자원", requirement: "第5个名所叫什么？", answer: "희망공원" },
  { question: "평거옥", requirement: "URL：交通停车[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1085403177/location?entry=pll&filter=parking" },
  { question: "평거옥", requirement: "URL:图片访问者[사진]> [방문자]", answer: "https://m.place.naver.com/restaurant/1085403177/photo?filterType=%EB%B0%A9%EB%AC%B8%EC%9E%90" },
  { question: "평거옥 진주본점", requirement: "地图周边公交车站网址中的10位数字", answer: "1085403177" },
  { question: "평거옥 진주본점", requirement: "URL:地图公交[지도]> [주변 정류장]", answer: "https://m.place.naver.com/restaurant/1085403177/location?filter=transportation" },
  { question: "평거옥 진주본점", requirement: "URL：地图停车场[지도]> [주차장]", answer: "https://m.place.naver.com/restaurant/1085403177/location?filter=parking" },
  { question: "평거옥 진주본점", requirement: "照片访客标签网址", answer: "https://m.place.naver.com/restaurant/1085403177/photo?filterType=%EB%B0%A9%EB%AC%B8%EC%9E%90" },
  { question: "천사곱창 발산본점", requirement: "URL：地图停车场[지도]> [주차장]", answer: "https://m.place.naver.com/restaurant/1056987472/location?entry=plt&filter=parking" },
  { question: "천사곱창 발산본점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1056987472/photo?filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "짚불구이 본가 방이점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1551619460/photo?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "짚불구이 본가 방이점", requirement: "URL: 地图公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1551619460/location?entry=plt&filterType=%EB%8F%99%EC%98%81%EC%83%81&filter=transportation" },
  { question: "짚불구이 본가 방이점", requirement: "数字URL[URL 주소]10자리까지 URL", answer: "https://m.place.naver.com/restaurant/1551619460" },
  { question: "짚불구이 본가 방이점", requirement: "图片视频剪辑网址地图相关中的10位数字", answer: "1551619460" },
  { question: "짚불구이 본가 방이점", requirement: "视频剪辑网址", answer: "https://m.place.naver.com/restaurant/1551619460/photo?entry=plt&filterType=%ED%81%B4%EB%A6%BD" },
  { question: "짚불구이 본가 방이점", requirement: "第3个停车场叫什么？", answer: "보광타워주차장" },
  { question: "짚불구이 본가 방이점", requirement: "数字URL[URL 주소]10자리까지 URL", answer: "https://m.place.naver.com/restaurant/1551619460" },
  { question: "퓨전포차 누룽지통닭", requirement: "照片访客标签网址", answer: "https://m.place.naver.com/restaurant/1363654262/photo?entry=plt&filterType=%EB%B0%A9%EB%AC%B8%EC%9E%90" },
  { question: "퓨전포차 누룽지통닭", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1363654262/photo?entry=plt&filterType=%EC%97%B0%EA%B4%80%EC%82%AC%EC%A7%84" },
  { question: "퓨전포차 누룽지통닭", requirement: "URL：地图停车场[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1363654262/location?entry=plt&filter=parking" },
  { question: "퓨전포차 누룽지통닭", requirement: "URL: 地图公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1363654262/location?entry=plt&filter=transportation" },
  { question: "퓨전포차 누룽지통닭", requirement: "地图停车场网址10位数字", answer: "1363654262" },
  { question: "퓨전포차 누룽지통닭", requirement: "附近的紫菜包饭叫什么?[김밥]", answer: "엄마정김밥" },
  { question: "따봉시래기 신현점", requirement: "第7个加油站叫GS什么名字？", answer: "GS칼텍스서현주유소" },
  { question: "따봉시래기 신현점", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1071672049/photo?filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "따봉시래기 신현점", requirement: "URL：地图停车场[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1071672049/location?filterType=%ED%81%B4%EB%A6%BD&filter=parking" },
  { question: "따봉시래기 신현점", requirement: "URL: 地图公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1071672049/location?filterType=%ED%81%B4%EB%A6%BD&filter=transportation" },
  { question: "따봉시래기 신현점", requirement: "【전화】12位连续电话[12개의]", answer: "050713881386" },
  { question: "따봉시래기 신현점", requirement: "URL：图片剪辑[사진]>[클립]", answer: "https://m.place.naver.com/restaurant/1071672049/photo?filterType=%ED%81%B4%EB%A6%BD" },
  { question: "따봉시래기 신현점", requirement: "网址10位数字", answer: "1071672049" },
  { question: "서울부띠끄", requirement: "URL：图片视频[사진]>[동영상]", answer: "https://m.place.naver.com/restaurant/1423886812/photo?entry=pll&filterType=%EB%8F%99%EC%98%81%EC%83%81" },
  { question: "서울부띠끄", requirement: "URL：地图停车场[지도]>[주차장]", answer: "https://m.place.naver.com/restaurant/1423886812/location?entry=pll&filter=parking" },
  { question: "서울부띠끄", requirement: "URL: 地图公交[지도]>[주변 정류장]", answer: "https://m.place.naver.com/restaurant/1423886812/location?entry=pll&filter=transportation" },
  { question: "서울부띠끄", requirement: "【전화】12位连续电话[12개의]", answer: "050713162091" },
  { question: "서울부띠끄", requirement: "URL：图片剪辑[사진]>[클립]", answer: "https://m.place.naver.com/restaurant/1423886812/photo?entry=pll&filterType=%ED%81%B4%EB%A6%BD" },
  { question: "서울부띠끄", requirement: "第5个停车场叫什么名字？", answer: "실로암빌딩주차장" },
  { question: "서울부띠끄", requirement: "网址10位数字", answer: "1423886812" },
  { question: "서울부띠끄", requirement: "第11个菜单的价格", answer: "14500" },
  { question: "서울부띠끄", requirement: "评论前10位含有[ㅅㅇㅅㅇ]的名字", answer: "서여사아" },
  { question: "레인지엑스 봉은사", requirement: "第4个地点", answer: "봉은공원" },
  { question: "연화갈매기", requirement: "第3个加油站叫什么GS？", answer: "동남주유소" },
  { question: "청와옥 본점", requirement: "第5个地点", answer: "방이동성당" },
  { question: "청와옥 사당직영점", requirement: "第5个地点", answer: "이수동산" },
  { question: "청와옥 양재직영점", requirement: "第5个地点", answer: "매헌시민의숲" },
  { question: "청와옥 을지로3가직영점", requirement: "第5个地点", answer: "명동문화공원" },
  { question: "청와옥 광명밤일마을점", requirement: "第5个地点", answer: "광명영회원" },
  { question: "황칠나라 풍년옥", requirement: "第6个地点", answer: "덕수공원" },
  { question: "황소식육실비식당 한우하이원", requirement: "第5个地点", answer: "도사곡휴양림" },
  { question: "리파인 하남미사점", requirement: "第2个加油站叫什么GS？", answer: "" },
  { question: "플러스싱크대", requirement: "第2个SK加油站什么名字？", answer: "자연에너지" },
  { question: "입주청소", requirement: "第2个加油站叫什么名字（ㅁㄴㅈㅇㅅ）", answer: "미니주유소" },
  { question: "입주청소", requirement: "第2个加油站叫什么GS？（ㅊㅅㄷㅈㅇㅅ）", answer: "차세대주유소" },
  { question: "재활용이사센터", requirement: "周边第4个名所叫什么？", answer: "계산동성당" },
  { question: "차알 광화문 디타워점", requirement: "周边第2个名所叫什么？", answer: "청진공원" },
  { question: "신의주찹쌀순대", requirement: "第5个名所", answer: "마루공원" },
  { question: "사쿠라테이엔 일산 메뉴", requirement: "前十名访客名字含\"ㅁㄷㄷ\"", answer: "만두댕" },
  { question: "한식뷔페&카페 봄날", requirement: "第21个菜单的价格", answer: "4800" },
  { question: "건강밥상심마니 배곧점", requirement: "［URL地址］从头到10个数字", answer: "https://m.place.naver.com/restaurant/1583227729" },
  { question: "플란치과의원 경기 동탄점 (플레이스 보고 퀴즈 맞추기)", requirement: "20241029", answer: "https://m.place.naver.com/hospital/1073004496/review/visitor?entry=pll" },
  { question: "청구경희한의원 구리 (플레이스 보고 퀴즈 맞추기)", requirement: "20241112", answer: "https://m.place.naver.com/hospital/32981850/review/visitor?entry=pll" },
  { question: "다라플란트치과 화정(플레이스 보고 퀴즈 맞추기)", requirement: "20241126", answer: "na" },
  { question: "수원이로운치과의원 (플레이스 보고 퀴즈 맞추기)", requirement: "20241202", answer: "https://m.place.naver.com/hospital/1126950654/review/visitor?entry=pll" },
  { question: "청구경희한의원 면목 (플레이스 보고 퀴즈 맞추기)", requirement: "20241209", answer: "https://m.place.naver.com/hospital/11532695/review/visitor?entry=pll" },
  { question: "매일여는한의원 울산본점 (플레이스 보고 퀴즈 맞추기)", requirement: "20241226", answer: "https://m.place.naver.com/hospital/1248317149/review/visitor?entry=pll" },
  { question: "닥터쁘띠의원 노원 (플레이스 보고 퀴즈 맞추기)", requirement: "20250318", answer: "https://m.place.naver.com/hospital/1670770936/review/visitor?entry=pll" },
  { question: "서울클래식치과의원(플레이스 보고 퀴즈 맞추기)", requirement: "20250326", answer: "https://m.place.naver.com/hospital/1401963896/review/visitor?entry=pll" },
  { question: "연세하이브치과의원 춘천 (플레이스 보고 퀴즈 맞추기)", requirement: "20250401", answer: "https://m.place.naver.com/hospital/1571715063/review/visitor?entry=pll" },
  { question: "서울에스마취통증의학과의원 (플레이스 보고 퀴즈 맞추기)", requirement: "20250401", answer: "https://m.place.naver.com/hospital/34826688/review/visitor?entry=pll" },
  { question: "시흥에어컨청소부부크린 (플레이스 보고 퀴즈 맞추기)", requirement: "20250404", answer: "https://m.place.naver.com/place/1984465128/review/ugc?entry=pll&type=list" },
  { question: "유디치과의원 성신여대 (플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/19535194/review/visitor?entry=pll" },
  { question: "법무법인 글로리 서울본사 (플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/place/1820100496/review/visitor?entry=pll" },
  { question: "서울척튼튼의원(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/1274140109/review/visitor?entry=pll" },
  { question: "플란치과의원 경기 수원점(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/1430030267/review/visitor?entry=pll" },
  { question: "빈센트치과의원(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/13031389/review/visitor?entry=pll" },
  { question: "플란치과의원 서울점(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/1430402581/review/visitor?entry=pll" },
  { question: "부평드림재활의학과의원(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/1034461898/review/visitor?entry=pll" },
  { question: "플란치과병원 부산점(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/1263686518/review/visitor?entry=pll" },
  { question: "온유치과의원(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/1438840829/review/visitor?entry=pll" },
  { question: "리더플란트치과의원 진주(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/1199622446/review/visitor?entry=pll" },
  { question: "매일여는 한의원 명지(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/1950677492/review/visitor?entry=pll" },
  { question: "조현난청연구소 보청기전문센터(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/place/21235478/review/visitor?entry=pll" },
  { question: "서울더고운치과의원 강일점(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/1291499437/review/visitor?entry=pll" },
  { question: "플란치과병원 인천 부평점(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/1393194552/review/visitor?entry=pll" },
  { question: "플란치과의원 인천 검단점(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/1698942918/review/visitor?entry=pll" },
  { question: "비타민의원 분당점(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/13182156/review/visitor?entry=pll" },
  { question: "청구경희한의원 은평(플레이스 보고 퀴즈 맞추기)", requirement: "20250407", answer: "https://m.place.naver.com/hospital/1025149185/review/visitor?entry=pll" },
  { question: "셀엑티브 루테인 플러스 마리골드 약국 30캡슐 3개월분 6개월분 [원산지:미국]", requirement: "产品编码", answer: "5229590839" },
  { question: "셀엑티브 루테인 플러스 마리골드 약국 30캡슐 3개월분 6개월분 [원산지:미국]", requirement: "ig地址", answer: "" },
  { question: "셀엑티브 루테인 플러스 마리골드 약국 30캡슐 3개월분 6개월분 [원산지:미국]", requirement: "制造商", answer: "필인터파마" },
  { question: "트립닷컴 인기특가상품(다낭)", requirement: "填空", answer: "핑거" },
  { question: "트립닷컴 인기특가상품", requirement: "酒店名填空", answer: "아리아케" },
  { question: "트립닷컴 인기특가상품(다낭)", requirement: "特价商品酒店中间两个字", answer: "핑거" },
  { question: "알콜스왑", requirement: "商品编号前5位", answer: "52641" },
  { question: "브라운 체온계", requirement: "商品编号前5位", answer: "52502" },
  { question: "한일선풍기 저소음", requirement: "商品编号", answer: "11942582533" },
  { question: "신일선풍기 BLDC", requirement: "商品编号", answer: "10269429391" },
  { question: "강아지알러지사료", requirement: "商品编号", answer: "11466461364" },
  { question: "임밍아웃복권", requirement: "商品编号", answer: "8918243652" },
  { question: "실내 탈취제", requirement: "商品编号", answer: "11901445142" },
  { question: "앰플", requirement: "商品编号", answer: "9380638463" },
  { question: "GV80 와이퍼", requirement: "商品编号", answer: "9890618957" },
  { question: "LF 쏘나타 와이퍼", requirement: "商品编号", answer: "9888362845" },
  { question: "가정용천국의계단", requirement: "商品信息第2个标签두번째", answer: "체력증진" },
  { question: "올뉴 투싼 와이퍼", requirement: "商品编号", answer: "10078949212" },
  { question: "제빙기", requirement: "商品编号", answer: "10180604421" },
  { question: "위닉스제로S", requirement: "商品信息第3个标签세번째", answer: "헤파필터" },
  { question: "타워프라임", requirement: "商品信息第3个标签세번째", answer: "헤파필터" },
  { question: "마사지젤", requirement: "商品编号", answer: "9392005357" },
  { question: "모기퇴치제", requirement: "商品编号", answer: "10453041170" },
  { question: "문서세단기 SC-4205", requirement: "商品编号后5位뒤 5자리를", answer: "93203" },
  { question: "등산화깔창", requirement: "商品第2个标签", answer: "런닝깔창" },
  { question: "카드단말기", requirement: "商品详细信息第5个标签", answer: "신용카드체크기" },
  { question: "LG360", requirement: "商品信息第1个标签", answer: "공기청정기필터" },
  { question: "엘지 에어컨필터 칸", requirement: "商品编码", answer: "10413827504" },
  { question: "삼성 H170D", requirement: "商品信息第2个标签", answer: "호환필터" },
  { question: "아이오닉 5 와이퍼", requirement: "商品编码", answer: "9890312222" },
  { question: "삼성 제트 먼지봉투", requirement: "商品编码", answer: "11122299965" },
  { question: "냉장고 탈취제", requirement: "商品编码", answer: "11904959862" },
  { question: "냉감베개커버", requirement: "商品编码", answer: "11705601984" },
  { question: "k5 와이퍼", requirement: "商品编码", answer: "9888063727" },
  { question: "유럽미장외부", requirement: "商品信息第2个标签", answer: "아트월" },
  { question: "스파크 와이퍼", requirement: "商品编码", answer: "9890463938" },
  { question: "삼성제트배터리", requirement: "商品编码", answer: "11553869212" },
  { question: "다이슨청소기헤드", requirement: "商品编码", answer: "11130759312" },
  { question: "유리세정제", requirement: "商品编码", answer: "9983870147" },
  { question: "아우디 A6와이퍼", requirement: "商品标签", answer: "10107572390" },
  { question: "스탠드다리미", requirement: "商品详细第2个标签", answer: "스티머" },
  { question: "커리쉴 쿨 허브 샴푸 1.6L", requirement: "商品信息第2个标签", answer: "상쾌한느낌" },
  { question: "싼타페 DM 와이퍼", requirement: "商品编码", answer: "9888398044" },
  { question: "삼성 G100D", requirement: "商品信息第3个标签", answer: "호환필터" },
  { question: "흑염소진액", requirement: "商品信息第5个标签", answer: "녹용진액" },
  { question: "흑염소진액", requirement: "商品信息第3个标签", answer: "녹용즙" },
  { question: "발마사지기", requirement: "商品信息第1个标签", answer: "발마사지" },
  { question: "커리쉴 에프터 살롱 케어 헤어팩 트리트먼트 250ml", requirement: "商品信息第2个标签", answer: "향수트리트먼트" },
  { question: "무선 쿨링 고데기", requirement: "商品信息第3个标签", answer: "판고데기" },
  { question: "발 받침대", requirement: "商品信息第3个标签", answer: "발받침" },
  { question: "아반떼 와이퍼", requirement: "商品编码", answer: "9888240329" },
  { question: "스포티지 와이퍼", requirement: "商品编码", answer: "9944984278" },
  { question: "펠리세이드 와이퍼", requirement: "商品编码", answer: "10078964669" },
  { question: "서랍형 수납장", requirement: "商品信息第1个标签", answer: "높은수납장" },
  { question: "안양 인덕원 하수구막힘", requirement: "周边名所第2个名字？", answer: "인덕원성당" },
  { question: "액상비타민 오쏘몰", requirement: "商品编码", answer: "431581787" },
  { question: "유럽미장", requirement: "第4个标签？", answer: "셀프인테리어" },
  { question: "카드단말기", requirement: "第2个标签", answer: "IC카드단말기" },
  { question: "카드단말기", requirement: "第1个标签", answer: "카드단말기" },
  { question: "Sleeveless T Shirts", requirement: "商品标签", answer: "306978662" },
  { question: "인삼", requirement: "商品信息第2个标签", answer: "아빠생신선물" },
  { question: "흑염소 진액", requirement: "商品信息第2个标签", answer: "흑염소엑기스" },
  { question: "스티머", requirement: "商品信息第1个标签", answer: "살균" },
  { question: "강아지눈영양제", requirement: "商品信息第2个标签", answer: "소형견" },
  { question: "식물성 멜라토닌", requirement: "商品信息第2个标签", answer: "시차적응" },
  { question: "스탠드다리미", requirement: "商品信息第1个标签", answer: "살균" },
  { question: "발마사지기", requirement: "商品信息第6个标签", answer: "발안마기" },
  { question: "유럽미장", requirement: "商品信息第3个标签", answer: "셀프시공" },
  { question: "발 받침대", requirement: "商品信息第2个标签", answer: "책상밑발판" },
  { question: "무이네 사막투어", requirement: "商品信息第5个标签", answer: "베트남" },
  { question: "햄스터 케이지", requirement: "商品信息第5个标签", answer: "고슴도치집" },
  { question: "수분크림 CL", requirement: "商品标签前6位", answer: "602277" },
  { question: "커리쉴 퍼펙션 컬크림 150ml", requirement: "商品信息第2个标签", answer: "산뜻한스타일" },
  { question: "커리쉴 실키 오일 세럼 손상 모발용 피치블로썸향", requirement: "商品标签", answer: "4995750207" },
  { question: "커리쉴 실키 오일 세럼 손상 모발용 피치블로썸향", requirement: "商品信息第2个标签", answer: "좋은향" },
  { question: "흑염소 진액", requirement: "商品信息第4个标签", answer: "보약" },
  { question: "냉감이불", requirement: "商品编码", answer: "11693289251" },
  { question: "커리쉴 새틴 앤 에어리 스프레이 300ml", requirement: "商品编码", answer: "6622683554" },
  { question: "디퓨저", requirement: "商品信息第1个标签", answer: "디퓨저추천" },
  { question: "쭈꾸미", requirement: "商品信息第3个标签", answer: "술안주" },
  { question: "춘천 닭갈비", requirement: "商品信息第2个标签", answer: "닭다리살" },
  { question: "수납장 렌지대", requirement: "商品信息第1个标签", answer: "렌지대수납장" },
  { question: "벤츠 E클래스 와이퍼", requirement: "商品标签", answer: "10042280978" },
  { question: "산업용제습기2", requirement: "商品标签", answer: "10193935884" },
  { question: "핸디스팀다리미", requirement: "商品信息第3个标签", answer: "가성비좋은" },
  { question: "핸디스팀다리미", requirement: "商品信息第2个标签", answer: "스티머" },
  { question: "맥그립", requirement: "商品信息第2个标签", answer: "헬스장" },
  { question: "술안주", requirement: "商品信息第1个标签", answer: "캠핑요리" },
  { question: "스캇나인 이노시톨", requirement: "商品信息第1个标签", answer: "이노시톨" },
  { question: "미니에어컨", requirement: "商品编码", answer: "8906669269" },
  { question: "술안주", requirement: "商品信息第1个标签", answer: "캠핑요리" },
  { question: "블루에어", requirement: "商品信息第2个标签", answer: "호환필터" },
  { question: "스탠드다리미", requirement: "商品信息第4个标签", answer: "여름" },
  { question: "핸디스팀다리미", requirement: "商品信息第4个标签", answer: "소형" },
  { question: "발안마기", requirement: "商品信息第6个标签", answer: "발지압기" },
  { question: "니로 필터", requirement: "商品编码", answer: "11287644151" },
  { question: "레이 와이퍼", requirement: "商品编码", answer: "9887765353" },
  { question: "산업용제습기3", requirement: "商品编码", answer: "10193935884" },
  { question: "족저근막염 깔창", requirement: "商品信息第2个标签", answer: "등산화깔창" },
  { question: "단백질보충제", requirement: "商品信息第3个标签", answer: "체력관리" },
  { question: "발뮤다 더퓨어", requirement: "商品信息第1个标签", answer: "공기청정기용" },
  { question: "실내 탈취제2", requirement: "商品编码", answer: "11901445142" },
  { question: "가정용천국의계단", requirement: "商品信息第4个标签", answer: "천국계단" },
  { question: "술안주", requirement: "商品信息第5个标签", answer: "집들이음식" },
  { question: "김서림방지제", requirement: "商品编码", answer: "10068676805" },
  { question: "가정용천국의계단", requirement: "商品信息第3个标签", answer: "홈트" },
  { question: "단백질보충제", requirement: "商品信息第2个标签", answer: "단백질다이어트" },
  { question: "체력관리", requirement: "商品信息第2个标签", answer: "단백질다이어트" },
  { question: "황태 소고기 소프트사료", requirement: "商品编码", answer: "6040169677" },
  { question: "패러글라이딩", requirement: "商品信息第6个标签", answer: "단양맛집" },
  { question: "책상 스탠드", requirement: "商品信息第6个标签", answer: "책상용" },
  { question: "독서실책상", requirement: "商品信息第4个标签", answer: "1인용책상" },
  { question: "독서실책상", requirement: "商品信息第2个标签", answer: "집중력책상" },
  { question: "클로렐라 덴탈껌", requirement: "商品编码", answer: "5736158323" },
  { question: "미니쿠퍼 와이퍼", requirement: "商品编码", answer: "10057846448" },
  { question: "미니세탁기", requirement: "商品编码", answer: "11984125920" },
  { question: "벽지페인트", requirement: "商品信息第2个标签", answer: "천연페인트" },
  { question: "선식", requirement: "商品信息第5个标签", answer: "미숫가루" },
  { question: "쭈꾸미", requirement: "商品信息第5个标签", answer: "집들이음식" },
  { question: "버뮤다 팬츠", requirement: "品目编号后2位", answer: "97" },
  { question: "무이네 사막투어", requirement: "商品信息第3个标签", answer: "무이네사막투어" },
  { question: "단백질보충제", requirement: "商品信息第4个标签", answer: "근육증가" },
  { question: "지쿠 반팔", requirement: "品目编号后3位", answer: "902" },
  { question: "LG 320", requirement: "商品信息第2个标签", answer: "호환필터" },
  { question: "변비 고양이사료", requirement: "商品编码", answer: "10537646485" },
  { question: "애습 반팔 셔츠", requirement: "品目编号后2位", answer: "ET" },
  { question: "독서실책상", requirement: "商品信息第6个标签", answer: "칸막이책상" },
  { question: "상세페이지제작", requirement: "商品信息第4个标签", answer: "나인디자인" },
  { question: "상세페이지제작", requirement: "商品信息第5个标签", answer: "웹디자인" },
  { question: "톤업선크림", requirement: "商品信息第2个标签", answer: "백탁없는" },
  { question: "발매트", requirement: "商品信息第4个标签", answer: "신발매트" },
  { question: "식물등", requirement: "商品编码", answer: "10321975132" },
  { question: "매실청", requirement: "商品信息第2个标签", answer: "매실농축액" },
  { question: "매실청", requirement: "商品信息第6个标签", answer: "매실진액" },
  { question: "멀티탭", requirement: "商品信息第4个标签", answer: "디자인멀티탭" },
  { question: "자석블럭", requirement: "商品信息第2个标签", answer: "아기선물" },
  { question: "맥세이프 그립톡", requirement: "商品信息第6个标签", answer: "아이폰거치대" },
  { question: "오리주물럭", requirement: "商品信息第3个标签", answer: "술안주" },
  { question: "석재볼라드", requirement: "商品信息最后1个标签", answer: "볼라드" },
  { question: "피그먼트 반팔", requirement: "品目编号后2位", answer: "CH" },
  { question: "발뮤다 에어엔진", requirement: "商品信息第1个标签", answer: "공기청정기필터" },
  { question: "코드제로먼지봉투", requirement: "商品编码", answer: "11087005199" },
  { question: "발마사지기", requirement: "商品信息第3个标签", answer: "발바닥마사지기" },
  { question: "쭈꾸미", requirement: "商品信息的第5个标签", answer: "집들이음식" },
  { question: "흑염소 진액", requirement: "商品信息的第5个标签", answer: "임신준비" },
  { question: "음식물쓰레기통", requirement: "商品编码", answer: "10042328617" },
  { question: "패러글라이딩", requirement: "商品信息最后1个标签", answer: "무료배송" },
  { question: "러닝양말", requirement: "商品编码", answer: "11582056223" },
  { question: "크루즈필터", requirement: "商品编码", answer: "8468470115" },
  { question: "티구안와이퍼", requirement: "商品编码", answer: "10046267343" },
  { question: "[퀴즈] 무선 쿨링 고데기", requirement: "商品信息的第3个标签", answer: "판고데기" },
  { question: "[정답입력]서랍형수납장", requirement: "商品信息的第1个标签", answer: "높은수납장" },
  { question: "[정답입력]모션데스크 pro", requirement: "商品编码前5位", answer: "75241" },
  { question: "[퀴즈] 버뮤다 와이드 팬츠 7부", requirement: "商品品号", answer: "BIN-97" },
  { question: "춘식이 디퓨저", requirement: "第1个产品选项的5个字", answer: "허그필로우" },
  { question: "여름양말", requirement: "商品编码", answer: "8748634051" },
  { question: "쿠쿠", requirement: "第1个标签", answer: "공기청정기필터" },
  { question: "[정답입력] 다용도 수납장", requirement: "第1个标签", answer: "도어수납장" },
  { question: "[정답입력] 밀리옷장", requirement: "第1个标签", answer: "시스템장" },
  { question: "[정답입력] 수제 화과자", requirement: "商品编号", answer: "11447322789" },
  { question: "위닉스타워Q", requirement: "第1个标签", answer: "공기청정기필터" },
  { question: "쭈꾸미", requirement: "商品信息的第1个标签", answer: "캠핑요리" },
  { question: "[정답입력]수납장 렌지대", requirement: "商品信息的第1个标签", answer: "렌지대수납장" },
  { question: "[정답입력] 서랍형 수납장", requirement: "商品信息的第1个标签", answer: "높은수납장" },
  { question: "패러글라이딩", requirement: "商品信息的第3个标签", answer: "패러글라이딩가격" },
  { question: "워셔액", requirement: "商品编号", answer: "11130308003" },
  { question: "물걸레청소기", requirement: "第4个标签", answer: "소형청소기" },
  { question: "발레코어 샌들", requirement: "货号", answer: "EBAL157365" },
  { question: "침구청소기", requirement: "第4个标签", answer: "살균" },
  { question: "침구청소기", requirement: "商品信息第6个标签", answer: "가정용" },
  { question: "스캇나인 아구아헤", requirement: "第2个标签", answer: "에스트로겐" },
  { question: "티구안 와이퍼", requirement: "商品编码", answer: "10046267343" },
  { question: "유럽미장", requirement: "第2个标签", answer: "페인트붓" },
  { question: "석재볼라드", requirement: "第2个标签", answer: "이동식볼라드" },
  { question: "더치커피", requirement: "第5个标签", answer: "아메리카노" },
  { question: "더치커피", requirement: "第4个标签", answer: "커피원액" },
  { question: "더치커피", requirement: "第1个标签", answer: "홈카페" },
  { question: "이뮨멀티비타민 오쏘몰", requirement: "商品编号", answer: "431581787" },
  { question: "코드제로 프리필터", requirement: "商品编码", answer: "10812469749" },
  { question: "워터밤물총", requirement: "商品编号", answer: "4614396256" },
  { question: "멀티탭", requirement: "第2个标签", answer: "멀티콘센트" },
  { question: "발 받침대", requirement: "商品信息的第1个标签", answer: "자세교정" },
  { question: "카드단말기", requirement: "第3个标签", answer: "카드체크기" },
  { question: "상세페이지제작", requirement: "第2个标签", answer: "상세페이지" },
  { question: "일회용 미니스푼 카페", requirement: "商品信息第6个标签", answer: "친환경수저" },
  { question: "소형청소기", requirement: "商品信息第3个标签", answer: "물청소기" },
  { question: "삼겹살", requirement: "商品信息第4个标签", answer: "선물세트" },
  { question: "산삼", requirement: "商品信息第2个标签", answer: "추석선물" },
  { question: "[정답입력] 디퓨저", requirement: "第1个标签", answer: "디퓨저추천" },
  { question: "발마사지기", requirement: "第4个标签", answer: "발바닥마사지기" },
  { question: "유럽미장셀프", requirement: "商品信息第2个标签", answer: "카페인테리어" },
  { question: "벽지페인트", requirement: "商品信息 最后一个标签", answer: "가구페인트" },
  { question: "책상 스탠드", requirement: "商品信息第2个标签", answer: "학습용" },
  { question: "책상 스탠드", requirement: "第1个标签", answer: "독서실" },
  { question: "발마사지기", requirement: "第2个标签", answer: "발마사지" },
  { question: "침구청소기", requirement: "商品信息第2个标签", answer: "이불청소" },
  { question: "50대남자선물 오쏘몰", requirement: "商品编码", answer: "9682315201" },
  { question: "수험생비타민 오쏘몰", requirement: "商品编码", answer: "10379475616" },
  { question: "석재볼라드", requirement: "商品信息第5个标签", answer: "원형볼라드" },
  { question: "익산 카페 베이글", requirement: "周边名所第2个名字？", answer: "배산" },
  { question: "대구 월성동 한우맛집", requirement: "周边第1个名所名字？", answer: "마을마당공원" },
  { question: "헛개진액", requirement: "商品信息的第1个标签", answer: "헛개열매" },
  { question: "sm6 와이퍼", requirement: "商品编码", answer: "10078572971" },
  { question: "Y존케어 미스트", requirement: "商品编码", answer: "10908970776" },
  { question: "물걸레청소기", requirement: "商品信息第2个标签", answer: "물걸레청소" },
  { question: "에어컨", requirement: "第1个标签", answer: "에어컨필터교체" },
  { question: "선물세트", requirement: "商品信息第2个标签", answer: "제주돼지" },
  { question: "식물등", requirement: "商品信息第5个标签", answer: "식물키우기" },
  { question: "팥찜질팩", requirement: "商品信息的第1个标签", answer: "배찜질팩" },
  { question: "휴나인 애사비", requirement: "商品信息的第1个标签", answer: "혈당조절" },
  { question: "삼겹살", requirement: "第5个标签", answer: "국내산" },
  { question: "결로방지페인트", requirement: "第5个标签", answer: "셀프페인트" },
  { question: "백향과", requirement: "第3个标签", answer: "백향과청" },
  { question: "신발 방수 스프레이", requirement: "商品编码", answer: "5367366790" },
  { question: "[정답입력] 캐디톡 골프 거리측정기", requirement: "第1个标签", answer: "골프거리측정기" },
  { question: "침구청소기", requirement: "第2个标签", answer: "이불청소" },
  { question: "상세페이지제작", requirement: "第4个标签", answer: "나인디자인" },
  { question: "독서실책상", requirement: "第2个标签", answer: "집중력책상" },
  { question: "발뮤다 에어엔진", requirement: "第1个标签", answer: "공기청정기필터" },
  { question: "책상 스탠드", requirement: "第6个标签", answer: "책상용" },
  { question: "[정답입력] 밀리옷장", requirement: "第1个标签", answer: "시스템장" },
  { question: "위닉스타워Q", requirement: "第1个标签", answer: "공기청정기필터" },
  { question: "스캇나인 아구아헤", requirement: "第2个标签", answer: "에스트로겐" },
  { question: "석재볼라드", requirement: "最后1个标签", answer: "볼라드" },
  { question: "선식", requirement: "第2个标签", answer: "식사대용선식" },
  { question: "더치커피", requirement: "第5个标签", answer: "아메리카노" },
  { question: "쿠쿠", requirement: "第1个标签", answer: "공기청정기필터" },
  { question: "유럽미장셀프", requirement: "第4个标签", answer: "셀프인테리어" },
  { question: "[정답입력] 캐디톡 골프 거리측정기", requirement: "第1个标签", answer: "골프거리측정기" },
  { question: "다슨청소기헤드", requirement: "商品编号", answer: "11130759312" },
  { question: "카피어랜드 타공기 LP-3031", requirement: "商品编码后5位", answer: "05832" },
  { question: "독서실책상", requirement: "第四个标签", answer: "고등학생책상" },
  { question: "선식", requirement: "第一个标签", answer: "블랙푸드선식" },
  { question: "춘식이 디퓨저", requirement: "商品第1选项字母名称", answer: "허그필로우" },
  { question: "에어컨", requirement: "第1个标签", answer: "에어컨필터교체" },
  { question: "일회용 미니스푼 카페", requirement: "第6个标签", answer: "친환경수저" },
  { question: "배변패드", requirement: "商品信息第1个标签", answer: "강아지배변패드" },
  { question: "백향과", requirement: "第3个标签", answer: "백향과청" },
  { question: "삼겹살", requirement: "第5个标签", answer: "국내산" },
  { question: "산삼", requirement: "第4个标签", answer: "명절선물" },
  { question: "휴나인 애사비", requirement: "第1个标签", answer: "혈당조절" },
  { question: "[정답입력]모션데스크 pro", requirement: "商品编号前5位", answer: "75241" },
  { question: "소형 가정용 코팅기 Qualmax H240 Multi", requirement: "商品编码后4位", answer: "7456" },
  { question: "신발장탈취제", requirement: "商品编码", answer: "11905014787" },
  { question: "[정답입력] 안양맛집", requirement: "步行最短距离", answer: "165" },
  { question: "[퀴즈] 법환포구맛집 (2)", requirement: "步行最短距离", answer: "151" },
  { question: "도라지청", requirement: "商品信息第1个标签", answer: "기침예방" },
  { question: "흑염소 진액", requirement: "第2个标签", answer: "흑염소엑기스" },
  { question: "프렌치 반팔셔츠", requirement: "商品代码前5个数字", answer: "34945" },
  { question: "더치커피", requirement: "第4个标签", answer: "커피원액" },
  { question: "여름바지", requirement: "商品代码前5个数字", answer: "34945" },
  { question: "더치커피", requirement: "第2个标签", answer: "액상커피" },
  { question: "주차번호판", requirement: "商品编号", answer: "9081815128" },
  { question: "배변패드", requirement: "第2个标签", answer: "강아지똥패드" },
  { question: "코웨이필터", requirement: "第1个标签", answer: "공기청정기필터" },
  { question: "신발장탈취제", requirement: "商品编码", answer: "11905014787" },
  { question: "글램 슬림 부츠컷 트레이닝", requirement: "S码下摆长度", answer: "27" },
  { question: "빨래건조대", requirement: "第2个标签", answer: "미니빨래건조대" },
  { question: "산삼", requirement: "第四个标签", answer: "명절선물" },
  { question: "백향과", requirement: "第三个标签", answer: "백향과청" },
  { question: "산삼", requirement: "第三个标签", answer: "추석선물세트" },
  { question: "강아지눈물사료", requirement: "商品编码", answer: "11217916820" },
  { question: "펠리세이드와이퍼", requirement: "商品编码", answer: "10078964669" },
  { question: "냉장고탈취제", requirement: "商品编码", answer: "11904959862" },
  { question: "아반떼와이퍼", requirement: "商品编码", answer: "9888240329" },
  { question: "새집증후군제거제", requirement: "商品编码", answer: "11905183186" },
  { question: "스파크와이퍼", requirement: "商品编码", answer: "9890463938" },
  { question: "변비고양이사료", requirement: "商品编码", answer: "10537646485" },
  { question: "스포티지와이퍼", requirement: "商品编码", answer: "9944984278" },
  { question: "햄스터케이지", requirement: "商品信息第5个标签", answer: "고슴도치집" },
  { question: "싼타페DM와이퍼", requirement: "商品编码", answer: "9888398044" },
  { question: "올뉴투싼와이퍼", requirement: "商品编码", answer: "10078949212" },
  { question: "레이와이퍼", requirement: "商品编码", answer: "9887765353" },
  { question: "[퀴즈] 경기도 화성 반송동 하수구막힘", requirement: "[주변] -> [명소]第2个景点名字", answer: "솔빛공원" },
  { question: "부천 옥길동 누수 ", requirement: "周边名所第3个名字？", answer: "범박동성당" },
  { question: "군포 당정동 하수구막힘", requirement: "周边名所第2个名字？", answer: "안양천" },
  { question: "김포하수구뚫음", requirement: "周边第1个名所名字？", answer: "오룡제" },
  { question: "해운대 맛집", requirement: "周边第3个名所叫什么？", answer: "와우산" },
  { question: "경기도 화성 반송동 하수구막힘", requirement: "周边名所第1个名字？", answer: "미추홀공원" },
  { question: "경기도광주하수구막힘", requirement: "周边第1个名所名字？", answer: "꽃봉" },
  { question: "죽전동하수구막힘", requirement: "周边名所第2个名字？", answer: "죽전중앙근린공원" },
  { question: "광명하수구막힘", requirement: "周边名所第2个名字？", answer: "일직수변공원" },
  { question: "일산하수구막힘", requirement: "周边名所第2个名字？", answer: "호수공원" },
  { question: "부천하수구뚫음", requirement: "周边名所第2个名字？", answer: "소향공원" },
  { question: "경기 광주 한의원", requirement: "周边名所第1个名字？", answer: "새능" },
  { question: "부평하수구막힘", requirement: "周边名所第2个名字？", answer: "쉼터놀이공원" },
  { question: "남양주하수구막힘", requirement: "周边名所第2个名字？", answer: "이석영광장" },
  { question: "홍대 맛집", requirement: "周边名所第1个名字？", answer: "경의선책거리" },
  { question: "삼성 F100D", requirement: "第3个标签", answer: "미세먼지제거" },
  { question: "연수구하수구막힘", requirement: "周边名所第1个名字？", answer: "미추홀공원" },
  { question: "홍대 맛집", requirement: "周边名所第2个名字？", answer: "홍대선원" },
  { question: "홍대 맛집", requirement: "周边名所第3个名字？", answer: "성룡사" },
  { question: "성수동 필러", requirement: "周边名所第2个名字？", answer: "청송소공원" },
  { question: "휴나인 구강 유산균 덴티 프레쉬 제로 엠지 MG 레프", requirement: "商品信息第2个标签", answer: "아기유산균" },
  { question: "포드 익스플로러 와이퍼", requirement: "商品编码", answer: "10057039820" },
  { question: "엘지에어컨필터", requirement: "商品编码", answer: "8520524848" },
  { question: "새집증후군 제거제", requirement: "商品编码", answer: "11905183186" },
  { question: "강아지 눈물사료", requirement: "商品编码", answer: "11217916820" },
  { question: "크루즈 필터", requirement: "商品编码", answer: "8468470115" },
  { question: "신발건조기", requirement: "商品编码", answer: "11379294297" },
  { question: "인천하수구뚫음", requirement: "周边名所第2个名字？", answer: "한아름근린공원" },
  { question: "야탑동하수구막힘", requirement: "周边名所第2个名字？", answer: "야탑공원" },
  { question: "일산동구하수구막힘", requirement: "周边名所第2个名字？", answer: "호수공원" },
  { question: "김포하수구뚫음", requirement: "周边名所第1个名字？", answer: "오룡제" },
  { question: "남동구하수구뚫음", requirement: "周边名所第2个名字？", answer: "한아름근린공원" },
  { question: "[정답입력] 사상 맛집", requirement: "", answer: "683" },
  { question: "[정답입력] 광안리 맛집", requirement: "最短距离", answer: "270" },
  { question: "[정답입력] 기장맛집", requirement: "", answer: "1.3" },
  { question: "[정답입력] 하남 맛집", requirement: "", answer: "2.2" },
  { question: "[정답입력] 여의도 맛집", requirement: "步行距离", answer: "1.9" },
  { question: "[정답입력] 광주장어맛집", requirement: "", answer: "190" },
  { question: "[정답입력] 용봉동 맛집", requirement: "", answer: "93" },
  { question: "[정답입력] 정자역맛집", requirement: "", answer: "290" },
  { question: "[정답입력] 안양맛집", requirement: "步行距离", answer: "165" },
  { question: "상수 고기집", requirement: "", answer: "1.1" },
  { question: "[정답입력] 여수 국수 맛집", requirement: "", answer: "2.5" },
  { question: "[퀴즈] 검단 오리 맛집", requirement: "距离公里数", answer: "1.2" },
  { question: "시흥 신천역 누수 9443", requirement: "第2个名所叫什么？", answer: "문화의거리" },
  { question: "경기도 안산 상록구 하수구막힘", requirement: "第2个名所叫什么？", answer: "이동공원" },
  { question: "[퀴즈]부천하수구뚫음", requirement: "第2个名所叫什么?", answer: "소향공원" },
  { question: "[퀴즈] 청라하수구막힘", requirement: "第1个景点", answer: "정서진공원" },
  { question: "[정답입력] 여의도 맛집", requirement: "最快距离", answer: "1.5" },
  { question: "종합광고대행사", requirement: "请按照ABC顺序在正确窗口输入[数字8位]", answer: "12822001" },
  { question: "[정답입력]경주 맛집", requirement: "最快距离", answer: "187" },
  { question: "인천맞춤정장", requirement: "第4个名所叫什么?", answer: "찬우물근린공원" },
  { question: "냉감불", requirement: "商品编码", answer: "11693289251" },
  { question: "강화도펜션 로맨틱", requirement: "最快步行距离", answer: "612" },
  { question: "블로그 url 공유미션", requirement: "URL链接", answer: "https://m.search.naver.com/search.naver?ssc=tab.m_blog.all&sm=mtb_jum&query=%EC%97%AC%EB%A6%84%EC%9D%98%EC%9B%90" },
  { question: "마포 정신과", requirement: "最快距离", answer: "643" },
  { question: "[퀴즈] 경기도 화성 반송동 하수구막힘", requirement: "第3个名胜", answer: "노작근린공원" },
  { question: "영도맛집", requirement: "最快距离", answer: "2.2" },
  { question: "제주 성게밥 맛집", requirement: "最快步行距离", answer: "429" },
  { question: "외도동 한치 맛집", requirement: "最快步行距离", answer: "1" },
  { question: "정자역맛집", requirement: "第2个名胜", answer: "분당가구거리" },
  { question: "법환포구맛집 (2)", requirement: "最快步行距离", answer: "156" },
  { question: "인천 구월동 미래로 누수", requirement: "最快距离", answer: "385" },
  { question: "평거동돼지국밥", requirement: "最快距离", answer: "1.5" },
  { question: "서면 맛집", requirement: "最快距离", answer: "345" },
  { question: "진해 맛집", requirement: "第2个名所", answer: "망개산" },
  { question: "홍대 카페", requirement: "最快步行距离", answer: "501" },
  { question: "[정답입력] 광안리 맛집", requirement: "最快步行距离", answer: "264" },
  { question: "[퀴즈] 부천하수구뚫음", requirement: "第2个名所", answer: "소향공원" },
  { question: "[퀴즈] 외도동 한치 맛집", requirement: "最快步行距离", answer: "1" },
  { question: "광명하수구막힘", requirement: "第2个名所", answer: "일직수변공원" },
  { question: "남양주하수구막힘", requirement: "第2个名所", answer: "이석영광장" },
  { question: "부산 맛집", requirement: "第2个名所", answer: "송정어울림체육공원" },
  { question: "[퀴즈] 부평하수구막힘", requirement: "第2个名所", answer: "쉼터놀이공원" },
  { question: "[퀴즈] 죽전동하수구막힘", requirement: "第2个名所", answer: "죽전중앙근린공원" },
  { question: "진주 술집", requirement: "第3个名所", answer: "초전공원" },
  { question: "[퀴즈] 언양 고기맛집", requirement: "最快步行距离", answer: "441" },
  { question: "[정답입력] 죽전네거리 맛집", requirement: "最快步行距离", answer: "1" },
  { question: "목포 맛집", requirement: "最快步行距离", answer: "926" },
  { question: "수원역 맛집", requirement: "第1个名所", answer: "수원다문화푸드랜드" },
  { question: "송도맛집", requirement: "最快距离", answer: "1.9" },
  { question: "남이섬풀빌라", requirement: "第1个景点", answer: "남도꽃정원" },
  { question: "남이섬풀빌라", requirement: "第3个景点 ", answer: "자라섬이화원" },
  { question: "[퀴즈] 연수구하수구막힘", requirement: "周边第1个名所", answer: "미추홀공원" },
  { question: "[퀴즈] 광명하수구막힘", requirement: "周边第2个名所", answer: "일직수변공원" },
  { question: "남이섬풀빌라", requirement: "附近第1个景点", answer: "남도꽃정원" },
  { question: "정자역맛집", requirement: "第3个名所", answer: "정자동카페골목" },
  { question: "수원역 맛집", requirement: "周年第4个名所？", answer: "임팍토 주짓수 수원역" },
  { question: "전주 맛집", requirement: "最快距离", answer: "1.3" },
  { question: "여의도 맛집", requirement: "最快步行距离", answer: "806" },
  { question: "서파장어랜드", requirement: "拨出12位电话号码", answer: "050713381239" },
  { question: "까몬 구미점", requirement: "附近超市的名字", answer: "코리아마트" },
  { question: "성남 한식 뷔페&카페", requirement: "第21个菜品价格", answer: "4800" },
  { question: "진해 맛집", requirement: "周边第1个名所", answer: "법혜사" },
  { question: "워터밤물총", requirement: "商品编号", answer: "4614396256" },
  { question: "[정답입력]다용도수납장", requirement: "第1个标签", answer: "도어수납장" },
  { question: "초전공원", requirement: "周年第4个名所？", answer: "가호꿈초롱공원" },
  { question: "고양시 화정동 하수구막힘", requirement: "周边第2个名所", answer: "화정중앙공원" },
  { question: "진주 맛집", requirement: "周边第1个名所", answer: "석류공원" },
  { question: "진해 맛집", requirement: "第3个名所", answer: "용재공원" },
  { question: "초전공원", requirement: "周年第4个名所？", answer: "가호꿈초롱공원" },
  { question: "진주 맛집", requirement: "周年第4个名所？", answer: "송림공원" },
  { question: "광안리 카페", requirement: "最快距离", answer: "112" },
  { question: "[퀴즈] 경기도광주하수구막힘", requirement: "第1个名所", answer: "꽃봉" },
  { question: "[퀴즈] 군포 당정동 하수구막힘", requirement: "第2个名所", answer: "안양천" },
  { question: "[퀴즈] 야탑동하수구막힘", requirement: "第2个名所", answer: "야탑공원" },
  { question: "[퀴즈] 일산동구하수구막힘", requirement: "第2个名所", answer: "호수공원" },
  { question: "[퀴즈] 연수구하수구막힘", requirement: "第1个景点", answer: "미추홀공원" },
  { question: "종합광고대행사", requirement: "8位数字", answer: "12822001" },
  { question: "[정답입력]전주 맛집", requirement: "最快距离[가OO]", answer: "1.5" },
  { question: "[퀴즈] 남양주하수구막힘", requirement: "第2个名所", answer: "이석영광장" },
  { question: "[퀴즈] 안양 인덕원 하수구막힘", requirement: "第2个名所", answer: "인덕원성당" },
  { question: "남이섬풀빌라", requirement: "第2个名所", answer: "자라섬출렁다리" },
  { question: "방배역 헬스장", requirement: "最快距离", answer: "534" },
  { question: "[정답입력]여의도 맛집", requirement: "最近距离", answer: "806" },
  { question: "[퀴즈] 법환포구맛집 (2)", requirement: "最快距离", answer: "156" },
  { question: "[퀴즈] 남동구하수구뚫음", requirement: "第2个名所", answer: "한아름근린공원" },
  { question: "까치산 맛집", requirement: "最快距离", answer: "범식당 까치산본점" },
  { question: "세종 맛집", requirement: "最快距离", answer: "915" },
  { question: "삼성궁 맛집", requirement: "最快距离", answer: "4" },
  { question: "연남동 맛집", requirement: "最快距离", answer: "631" },
  { question: "제주 중문 장어맛집", requirement: "最快距离", answer: "758" },
  { question: "유럽미장", requirement: "第4个标签", answer: "셀프인테리어" },
  { question: "남이섬 풀빌라", requirement: "周边第2个场所", answer: "자라섬출렁다리" },
  { question: "기장 맛집", requirement: "最快距离", answer: "713" },
  { question: "[퀴즈] 검단 오리 맛집", requirement: "步行最快距离", answer: "1.2" },
  { question: "[정답입력]영도맛집", requirement: "步行最快距离", answer: "2" },
  { question: "[퀴즈] 검단 오리 맛집", requirement: "步行最快距离", answer: "1.2" },
  { question: "법환포구맛집", requirement: "最短步行距离", answer: "156" },
  { question: "닥터초이스맞추기 5.23", requirement: "콜라겐、规格20g*14", answer: "https://m.shopping.naver.com/popup/channels/2uA9MdKLJI01IwuPDuBHM/products/9163172944/review?from=smartstore&prevUrl=https%3A%2F%2Fm.smartstore.naver.com%2Fdrchoice%2Fproducts%2F9163172944%3FNaPm%3Dct%253Dmca9jh1k%257Cci%253D32af54539a432e4e574675fe133ade4b290ee1de%257Ctr%253Dslsc%257Csn%253D9346804%257Chk%253Dc47607db4eb108a0049310ab564f27765baa42ed%26nl-query%3D%25EC%25BD%259C%25EB%259D%25BC%25EA%25B2%2590%23REVIEW&scrollToReview=true" },
  { question: "90포 흑염소헬스 맞추기 5.28", requirement: "흑염소진액", answer: "https://m.shopping.naver.com/popup/channels/2sWE0IFZRjeVaST1aMrxz/products/10393765783/review?from=smartstore&prevUrl=https%3A%2F%2Fm.smartstore.naver.com%2Fwealthandhealth%2Fproducts%2F10393765783%3Fnl-query%3D%25ED%259D%2591%25EC%2597%25BC%25EC%2586%258C%25EC%25A7%2584%25EC%2595%25A1%26nl-ts-pid%3Dja51jwqosKwssZ3kPYNsssssseV-425568%26NaPm%3Dct%253Dmc1ofbm8%257Cci%253D4a90a6d53ac6d88d05221015bc94acfee51ff450%257Ctr%253Dsls%257Csn%253D3760978%257Chk%253D6e933125dfeb763232d90c4d19104c6d6fd598d1%23REVIEW&scrollToReview=true" },
  { question: "아기섬유유연제 맞추기 6.24", requirement: "아기섬유유연제", answer: "https://m.shopping.naver.com/popup/channels/2sWDzFBLrN6fCHRy8Iewx/products/10765744840/review?from=brandstore&prevUrl=https%3A%2F%2Fm.brand.naver.com%2Ffrankliin%2Fproducts%2F10765744840%3FNaPm%3Dct%253Dmcaceafk%257Cci%253D94a9209a7f46541e9341a7327b1faac5db9220eb%257Ctr%253Dslsbrc%257Csn%253D1764796%257Chk%253Dcc0cc4461224a0847b5f3f0d0a7b25f1ff759bed%26nl-query%3D%25EC%2595%2584%25EA%25B8%25B0%25EC%2584%25AC%25EC%259C%25A0%25EC%259C%25A0%25EC%2597%25B0%25EC%25A0%259C%23REVIEW&scrollToReview=true" },
  { question: "유아캡슐세제 맞추기 6.24", requirement: "유아캡슐세제、规格8g*40", answer: "https://m.shopping.naver.com/popup/channels/2sWDzFBLrN6fCHRy8Iewx/products/11871753099/review?from=brandstore&prevUrl=https%3A%2F%2Fm.brand.naver.com%2Ffrankliin%2Fproducts%2F11871753099%3FNaPm%3Dct%253Dmcaccpc0%257Cci%253Ddd5c33d896edda4bfbec89687e9b8a57313954f7%257Ctr%253Dslsc%257Csn%253D1764796%257Chk%253D650ebd57c59670119f6826a6204e95a69fd82213%26nl-query%3D%25EC%259C%25A0%25EC%2595%2584%25EC%25BA%25A1%25EC%258A%2590%25EC%2584%25B8%25EC%25A0%259C%23REVIEW&scrollToReview=true" },
  { question: "피토메스남자화장품의 일이와삼 맞추기 6.24", requirement: "남자화장품", answer: "https://m.smartstore.naver.com/12wa3/products/10756393386?NaPm=ct%253Dmc2wyft4%257Cci%253D7a2f85f336bf2a6a851e7a44790d8bc79de01da8%257Ctr%253Dslsbrc%257Csn%253D11343394%257Chk%253D5e039809a189f4e28d6bddd2e8ee85a2422432c9&nl-query=%EB%82%A8%EC%9E%90%ED%99%94%EC%9E%A5%ED%92%88#REVIEW" },
  { question: "스탠맨해머전동드릴 맞추기 6.27", requirement: "전동드릴세트", answer: "https://m.shopping.naver.com/popup/channels/2sWDyDLxIuW8R3kKfwqXM/products/8810886907/review?from=smartstore&prevUrl=https%3A%2F%2Fm.smartstore.naver.com%2Fsunflowershop%2Fproducts%2F8810886907%3FNaPm%3Dct%253Dmc76kg20%257Cci%253D87682c36b405901ba9d5ba24bd40d1382473c9de%257Ctr%253Dslsc%257Csn%253D1022775%257Chk%253D7e1b551e8cb025edafb85d5f6911572fae5e1cc9%26nl-query%3D%25EC%25A0%2584%25EB%258F%2599%25EB%2593%259C%25EB%25A6%25B4%25EC%2584%25B8%25ED%258A%25B8%23REVIEW&scrollToReview=true" },
  { question: "폴로커플pk 맞추기 6.24", requirement: "폴로커플pk", answer: "https://m.shopping.naver.com/popup/channels/2sWE0yBqhtlMjoCxTjfRT/products/6201722643/review?from=smartstore&prevUrl=https%3A%2F%2Fm.smartstore.naver.com%2Fmypol%2Fproducts%2F6201722643%3FNaPm%3Dct%253Dmcj180i0%257Cci%253D56f1c2d3622a084a35a6392bb3b89e37b38e8a43%257Ctr%253Dslsl%257Csn%253D5236614%257Chk%253D50c69cecbdd127456cf257997cafe7b50ef3418e%26nl-au%3D1f2a9cde47594c808b32041dd47c886a%26nl-query%3D%25ED%258F%25B4%25EB%25A1%259C%25EC%25BB%25A4%25ED%2594%258Cpk%23REVIEW&reviewId=4748501557&scrollToReview=true" },
  { question: "투인원에어컨 더베스트에어컨 맞추기 5.21", requirement: "삼성2in1에어컨", answer: "https://m.shopping.naver.com/popup/channels/2sWDwqzMeA1zhR1V0Icnn/products/10393172294/review?from=smartstore&prevUrl=https%3A%2F%2Fm.smartstore.naver.com%2Fdb-bestaircon%2Fproducts%2F10393172294%3FNaPm%3Dct%253Dmcj1ew6o%257Cci%253D4572bfa237ca15a2f936a219419f1f5477611d5a%257Ctr%253Dslsl%257Csn%253D1036370%257Chk%253D674bc8613f132c42b7400f5312313f5eff962d80%26nl-au%3D6dab6676a112488bb842aa1b72468297%26nl-query%3D%25EC%2582%25BC%25EC%2584%25B12in1%25EC%2597%2590%25EC%2596%25B4%25EC%25BB%25A8%23REVIEW&reviewId=4737967858&scrollToReview=true" },
  { question: "실리콘 수영가방 맞추기 5.30", requirement: "방수 수영가방", answer: "https://m.shopping.naver.com/popup/channels/2sWDwUMisG9enCAT8F9Jq/products/11873387986/review?from=smartstore&prevUrl=https%3A%2F%2Fm.smartstore.naver.com%2Fsneff%2Fproducts%2F11873387986%3FNaPm%3Dct%253Dmcj1mjnc%257Cci%253D504100ad32ef5f733df66a66db02c997df1fbc53%257Ctr%253Dslct%257Csn%253D575146%257Chk%253Df48e4cde4faf0b8b5e75c999c40a7fd1dd9a3fc7%26nl-query%3D%25EC%258B%25A4%25EB%25A6%25AC%25EC%25BD%2598%2B%25EC%2588%2598%25EC%2598%2581%25EA%25B0%2580%25EB%25B0%25A9%2B%25EB%25A7%259E%25EC%25B6%2594%25EA%25B8%25B0%2B5.30%23REVIEW&reviewId=4753861119&scrollToReview=true" },
  { question: "피토메스남자화장품의 마레몰 맞추기 5.29", requirement: "남자화장품", answer: "https://m.shopping.naver.com/popup/channels/2tumFAXn0xb7Du8mhs0RE/products/11183529510/review?from=smartstore&prevUrl=https%3A%2F%2Fm.smartstore.naver.com%2Fmare_mall%2Fproducts%2F11183529510%3FNaPm%3Dct%253Dmcj1s5t4%257Cci%253D08d10c082b71bf135b3fd166498b77068302a19b%257Ctr%253Dslbrc%257Csn%253D9144104%257Chk%253D6a93738b711d54bd756e3303e93b506512782fdd%26nl-query%3D%25EB%2582%25A8%25EC%259E%2590%25ED%2599%2594%25EC%259E%25A5%25ED%2592%2588%23REVIEW&reviewId=4752299693&scrollToReview=true" },
  { question: "43인치스탠바이미 맞추기 6.29", requirement: "43인치스탠바이미", answer: "https://m.shopping.naver.com/popup/channels/2sWDvSd4wPJxgNNsRVEu9/products/9764204740/review?from=smartstore&prevUrl=https%3A%2F%2Fm.smartstore.naver.com%2Fflatron%2Fproducts%2F9764204740%3FNaPm%3Dct%253Dmcj1xcjc%257Cci%253D91985b547977e64e7e4c2b380518bbeb673dd5e1%257Ctr%253Dslsl%257Csn%253D199791%257Chk%253D9cd0e74673bc2a745a6cebe9b7214b81bb7ce406%26nl-au%3D9f9977712f0b4e4ea864db91fd4f2562%26nl-query%3D43%25EC%259D%25B8%25EC%25B9%2598%25EC%258A%25A4%25ED%2583%25A0%25EB%25B0%2594%25EC%259D%25B4%25EB%25AF%25B8%23REVIEW&reviewId=4750569967&scrollToReview=true" },
  { question: "논가스용접기 200프로 맞추기 6.30", requirement: "논가스용접기", answer: "https://m.shopping.naver.com/popup/channels/2sWDxuuDjl7CHDdgpnu6g/products/10109592241/review?from=smartstore&prevUrl=https%3A%2F%2Fm.smartstore.naver.com%2Fsoyatool%2Fproducts%2F10109592241%3Fnl-query%3D%25EB%2585%25BC%25EA%25B0%2580%25EC%258A%25A4%25EC%259A%25A9%25EC%25A0%2591%25EA%25B8%25B0%26nl-ts-pid%3Djb6QewprfMlss5wSLNKssssstxd-146852%26NaPm%3Dct%253Dmcj73jgw%257Cci%253D6e9be67f6757c602a25e81edc7e129c864f9902b%257Ctr%253Dsls%257Csn%253D935574%257Chk%253D2b25adfec81beaaee866a88ab164914fb2325059%23REVIEW&reviewId=4743413397&scrollToReview=true" },
  { question: "부천 옥길동 누수", requirement: "周边名所第3个叫什么？", answer: "범박동성당" },
  { question: "클로렐라 덴탈껌", requirement: "商品编号", answer: "5736158323" },
  { question: "티구안 와이퍼", requirement: "商品编号", answer: "10046267343" },
  { question: "코드제로 프리필터", requirement: "商品编号", answer: "10812469749" },
  { question: "미니세탁기", requirement: "商品编号", answer: "11984125920" },
  { question: "물걸레청소기", requirement: "第3个标签", answer: "물청소기" },
  { question: "황태 소고기 소프트사료", requirement: "商品编号", answer: "6040169677" },
  { question: "[정답입력] 수제 화과자", requirement: "商品编号", answer: "11447322789" },
];
